// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace AssemblyCSharp
{
		public class DoorMaster
		{
			private static readonly DoorMaster instance = new DoorMaster();
				
				
			static DoorMaster()
			{
			}
				
			private DoorMaster()
			{
			}
				
			public static DoorMaster Instance
			{
				get
				{
					return instance;
				}
			}
			
		public void StartTransition()
		{
			TransitionStarted (this, null);
		}

		public void GoTransition()
		{
			TransitionGoing (this, null);	
		}

		public void EndTransition()
		{
			TransitionEnded (this, null);
		}

			public event TransitionStartedHandler TransitionStarted;
			public event TransitionGoingHandler TransitionGoing;
			public event TransitionEndedHandler TransitionEnded;
		}
}

